HW02 Мартынов Максим
maxmartynov08/Linux-basics-2020 pull request #2
Opened 2020-09-23 11:28 UTC by maxmartynov08

В `test08.py` вроде бы есть ошибки. Он берет код не из `task08.sh`, а из `task06.sh` + получаются разные ответы (у меня на 1 больше)

2020-09-30 14:39 UTC, sloboegen98 commented on seminar02/task02/task02.sh
> +cat numbers.txt | sort | uniq | wc -l
Можно ведь без ```cat``` обойтись, ```sort``` умеет работать с файлом. И у ```sort``` есть ключик, который позволяет не использовать ```uniq```

2020-09-30 14:41 UTC, sloboegen98 commented on seminar02/task03/task03.sh
> +ps | grep "tail -f /dev/null" | head -c 5 | xargs kill
Нужно еще отфильтровывать сам процесс, с помощью ```grep -v grep```. И нельзя же полагаться, что ```PID``` содержит 5 цифр...

2020-09-30 14:44 UTC, sloboegen98 requested changes
Все засчитываю, кроме задания 3. Поправь, пожалуйста

2020-09-30 21:23 UTC, maxmartynov08 commented on seminar02/task03/task03.sh
> +ps | grep "tail -f /dev/null" | head -c 5 | xargs kill
Поправил, хотя все равно не понял, что значит `grep -v grep`

2020-10-07 22:26 UTC, sloboegen98 approved these changes
ok, в табличке отразил

2020-10-07 22:26 UTC, closed without merging